openapi: 3.0.1
info:
  title:  API
  version: 1.0.0-alpha.1
  description: |-
    This is a API documentation

    ### 📝 Changelog
    * Add API specifications

servers:
  - url: '{host}/api/v1'
    variables:


security:
  - token: []
