name: Build Swagger Docker Images

on:
  workflow_dispatch:
    inputs:
      admin_version:
        description: 'Admin Swagger 버전 (예: 1.0.0-alpha.1). 입력하지 않으면 최신 버전을 사용합니다.'
        required: false
        type: string
      api_version:
        description: 'API Swagger 버전 (예: 1.0.0-alpha.1). 입력하지 않으면 최신 버전을 사용합니다.'
        required: false
        type: string

jobs:
  find-swagger-paths:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [admin, api]
    outputs:
      admin_path: ${{ steps.set-path.outputs.admin_path }}
      api_path: ${{ steps.set-path.outputs.api_path }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: yq 설치
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Swagger 경로 찾기
        id: find_path
        run: |
          swagger_path=""
          version_var="INPUT_${{ matrix.context | upper }}_VERSION"
          version=${!version_var}

          if [[ -z "$version" ]]; then
            # 최신 버전 찾기
            swagger_path=$(find ${{ matrix.context }}/src/main/resources/static/swagger -name spec.yaml | while read -r file; do
              version=$(yq eval '.info.version' "$file");
              echo "$version $file";
            done | sort -V | tail -n 1 | awk '{print $2}')
          else
            # 입력받은 버전 찾기
            swagger_path=$(find ${{ matrix.context }}/src/main/resources/static/swagger -name spec.yaml | while read -r file; do
              version=$(yq eval '.info.version' "$file");
              if [[ "$version" == "$version" ]]; then
                echo "$file";
              fi
            done)
          fi

          if [[ -z "$swagger_path" ]]; then
            echo "Swagger 파일을 찾을 수 없습니다: ${{ matrix.context }}" >&2
            exit 1
          fi
          echo "${{ matrix.target }}_path=$SWAGGER_PATH" >> $GITHUB_OUTPUT

  build-docker-images:
    needs: find-swagger-paths
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      # - name: Docker 이미지 빌드
      #   run: |
      #     docker build \
      #       --build-arg ADMIN_SWAGGER_PATH=$ADMIN_SWAGGER_PATH \
      #       --build-arg API_SWAGGER_PATH=$API_SWAGGER_PATH \
      #       -t swagger-ui-image .

      - name: Print
        run: |
          echo "admin path :: ${{eeds.find-swagger-paths.outputs.admin_path}}"
          echo "api path :: ${{eeds.find-swagger-paths.outputs.api_path}}"