name: Build Swagger Docker Images

on:
  workflow_dispatch:
    inputs:
      admin_version:
        description: 'Admin Swagger 버전 (예: 1.0.0-alpha.1). 입력하지 않으면 최신 버전을 사용합니다.'
        required: false
        type: string
      api_version:
        description: 'API Swagger 버전 (예: 1.0.0-alpha.1). 입력하지 않으면 최신 버전을 사용합니다.'
        required: false
        type: string

jobs:
  find-swagger-paths:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [admin, api]
    outputs:
      admin_path: ${{ steps.set-path.outputs.admin_path }}
      api_path: ${{ steps.set-path.outputs.api_path }}
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: yq 설치
        run: | 
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: Swagger 경로 찾기
        id: find_path
        run: |
          TARGET_DIR='${{ matrix.target }}/src/main/resources/static/swagger'
          INPUT_VERSION=${{ github.event.inputs[format('{0}_version', matrix.target)] || '.*' }}
          SWAGGER_PATH=$(find $TARGET_DIR -type f -name "spec.yaml" | \
                          xargs grep -l "version: $INPUT_VERSION" | sort | tail -n 1)
          if [ -z "$SWAGGER_PATH" ]; then
            echo "Error: Swagger 경로를 찾을 수 없습니다. 대상: ${{ matrix.target }}"
            exit 1
          fi
          echo "${{ matrix.target }}_path=$SWAGGER_PATH" >> $GITHUB_OUTPUT

  build-docker-images:
    needs: find-swagger-paths
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      # - name: Docker 이미지 빌드
      #   run: |
      #     docker build \
      #       --build-arg ADMIN_SWAGGER_PATH=$ADMIN_SWAGGER_PATH \
      #       --build-arg API_SWAGGER_PATH=$API_SWAGGER_PATH \
      #       -t swagger-ui-image .

      - name: Print
        run: |
          echo "admin path :: ${{needs.find-swagger-paths.outputs.admin_path}}"
          echo "api path :: ${{needs.find-swagger-paths.outputs.api_path}}"