name: NEW | Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-${{ github.event.inputs.int-env }}-${{ github.event.inputs.app }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APPS: "api admin batch"
  KEY: "admin"
  names: |
    {
      "admin": "app-admin",
      "front": "app-front",
      "batch": "batch",
      "api": "api"
    }

jobs:
  filter-build-targets:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        env:
          NAMES_JSON: ${{ env.names }} # JSON 문자열을 환경 변수로 설정
        run: |
          echo "env.names :::: $NAMES_JSON"
          echo "env.names to JSON :::: $(echo "$NAMES_JSON" | jq .)" # JSON 변환 후 출력
          echo "env.names get front :::: $(echo "$NAMES_JSON" | jq -r '.front')" # 특정 키 값 출력
