name: NEW | Deploy

on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: 'target application'
        required: true
        options:
          - API
          - ADMIN
          - BATCH
        
concurrency:
  group: deploy-${{ github.event.inputs.int-env }}-${{ github.event.inputs.app }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APPS: "api admin batch"
  KEY: "admin"
  names: |-
    ${{ fromJson('{
      "ADMIN": {
            "app": "admin",
            "service": "admin-api",
            "name": "ADMIN"
        },
      "BATCH": {
            "app": "batch",
            "service": "batch",
            "name": "BATCH"
        },
      "API": {
            "app": "api",
            "service": "api",
            "name": "API"
        }
    }')[github.event.inputs.app] }}

jobs:
  filter-build-targets:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        env:
          NAMES_JSON: ${{ env.names }} # JSON 문자열을 환경 변수로 설정
        run: |
          echo "env.names :::: $NAMES_JSON"
          echo "env.names to JSON :::: $(echo "$NAMES_JSON" | jq .)" # JSON 변환 후 출력
          echo "env.names get front :::: $(echo "$NAMES_JSON" | jq -r '.app')" # 특정 키 값 출력
