name: NEW | Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-${{ github.event.inputs.int-env }}-${{ github.event.inputs.app }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APPS: "api admin batch"
  KEY: "admin"
  names: |-
    ${{ toJson('{
      "admin": "app-admin",
      "front": "app-front",
      "batch": "batch",
      "api": "api"
    }') }}
  sub-service-name: |-
    ${{ fromJson('{
      "ADMIN": "app-admin",
      "FRONT": "app-front",
      "BATCH": "batch",
      "API": "api"
    }') }}
  

jobs:
  filter-build-targets:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "env.names :::: ${{ env.names }}"
          echo "env.names to JSON :::: ${{ fromJson(env.names) }}"
          echo "env.names get admin :::: ${{ fromJson(env.names)['front'] }}"
          echo "sub-service-name :: ${{ env.sub-service-name }}"
