name: NEW | Deploy

on:
  push:
    branches:
      - master

run-name: ${{ github.workflow }} ${{ github.event.inputs.is-manual && ' | MANUAL' || ''}}

concurrency:
  group: deploy-${{ github.event.inputs.int-env }}-${{ github.event.inputs.app }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APPS: "api admin batch"
  names: |-
    '{
      "admin": "app-admin",
      "front": "app-front",
      "batch": "batch",
      "api": "api"
    }'
  

jobs:
  filter-build-targets:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "env.names :::: ${{ env.names }}"
          echo "env.names to JSON :::: ${{ fromJson(env.names) }}"
